### PR TITLE
Company page

### LINKED ISSUE #110: Website - Company page

### PR DESCRIPTION
**Pull request by momegas**
Resolves #110

### CODE REVIEW

**Comment by momegas** [comment]
Screenshot 2021-11-02 at 11 14 11 PM
Screenshot 2021-11-02 at 11 14 17 PM
Screenshot 2021-11-02 at 11 14 21 PM

**Comment by ksiabani** [comment]
Overall is nice, but you have a lot of typos (use a speller bro 😛 ) : 

- We help CTOs and.... `to drive home early`
- `what matters` not `maters`
- Use more commas (again use a speller)
- The phrase `We deliver what we promised, on the time we promised it` is wrong (this is not on you, it's wrong in the strategy as well). I propose: `We deliver what promised, when promised or your money back`
- Also, you give two promises there, so make them clear they are two. Use bullets for example
- Suggestion: `Our big audacious goal` instead of: `the goal of the company is`
- Use `:` after `Number 4` and `Last but not least`

Also: 

- Where is `the team` section? Did you add Charis and Eli?
- What about the address? Did you change to the new address?

Finally, there is a bug in the live site when you click on the `Contact us` button, it doesn't scroll to the contact form. It looks for a section ID of `contact2` and I think the ID of the contact section is different.

**Comment by momegas** [comment]
I shouldn't be doing work late at night....

**Comment by momegas** [comment]
@ksiabani please have a look at the texts. No team images yet I'm afraid 😧

**Pull request merged**
